version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: P9l12&zD8A82G!(0z
      MYSQL_DATABASE: blogapp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blogapp-network

  api:
    build:
      context: .
    container_name: webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5174:8080"
    depends_on:
      - mysql
    networks:
      - blogapp-network

volumes:
  mysql_data:

networks:
  blogapp-network:
    driver: bridge
